#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$(dirname $0)/../common/functions"

case "$1" in
  slack:set)
    [[ -z $2 ]] && echo "Please specify an app to run the command on" && exit 1
    verify_app_name "$2"
    APP="$2"
    if [[ -z $3 ]]; then
      rm "$DOKKU_ROOT/$APP/SLACK_URL"
    else
      echo "$3" > "$DOKKU_ROOT/$APP/SLACK_URL"
    fi
    ;;

  slack:get)
    [[ -z $2 ]] && echo "Please specify an app to run the command on" && exit 1
    verify_app_name "$2"
    APP="$2"
    cat "$DOKKU_ROOT/$APP/SLACK_URL"
    ;;

  help)
    cat && cat<<EOF
    slack:set <app> <url>                           Set Slack service URL
    slack:get <app>                                 Display Slack service URL
EOF
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;
esac
