#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"
IMAGE="$2"
HOSTNAME=$(hostname -f)

if [ -f $DOKKU_ROOT/$APP/SLACK_URL ]; then
  echo "-----> Notifying Slack ..."
  URL=$(cat $DOKKU_ROOT/$APP/URL)
  SLACK_URL=$(cat $DOKKU_ROOT/$APP/SLACK_URL)
  SLACK_MESSAGE="Deployed $APP to $HOSTNAME via $URL"
  SLACK_JSON="{\"text\": \"$SLACK_MESSAGE\", \"color\": \"good\", \"mrkdwn_in\": [\"text\"]}"
  SLACK_RESULT=`curl -s -d "payload=$SLACK_JSON" "${SLACK_URL}" -w "%{http_code}"`
  echo $SLACK_RESULT
fi
